version: 2
jobs:
    build:
        docker:
            - image: electronuserland/builder:wine
        parallelism: 1
        working_directory: ~/yixiyimeng/win
        steps:
            - checkout
            - attach_workspace:
                  at: ~/yixiyimeng/win
            - restore_cache:
                  key: v1-yarn-{{ checksum "package.json" }}
            - run: npm install
            - save_cache:
                  key: v1-yarn-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules
            - run: npm run build
            - store_artifacts:
                  path: ~/yixiyimeng/win/build
